Metrics/BlockLength:
  Exclude:
    - '**/*.gemspec'
    - '**/*.rake'
    - 'config/environments/*.rb'
    - 'config/initializers/simple_form_bootstrap.rb'
    - 'config/routes.rb'
    - 'spec/**/*.rb'

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*.rb'

Style/FrozenStringLiteralComment:
  Exclude:
    - 'bin/**/*'
