Metrics/BlockLength:
  Exclude:
    - '**/*.gemspec'
    - '**/*.rake'
    - 'config/routes.rb'
    - 'spec/**/*.rb'

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*.rb'

Style/FrozenStringLiteralComment:
  Exclude:
    - 'bin/**/*'
